// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6N2HzBD0VPKUIaoTZeljOl_XPHt-V2Ag',
    appId: '1:424836022854:web:088cb268bcfbbfd56f0047',
    messagingSenderId: '424836022854',
    projectId: 'smart-tourism-app-4556',
    authDomain: 'smart-tourism-app-4556.firebaseapp.com',
    storageBucket: 'smart-tourism-app-4556.firebasestorage.app',
    measurementId: 'G-C6D0BS75R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQm2P-rJaC4Nc15ByERT-R1mk-3GKSXJo',
    appId: '1:424836022854:android:343ceaf922cc232e6f0047',
    messagingSenderId: '424836022854',
    projectId: 'smart-tourism-app-4556',
    storageBucket: 'smart-tourism-app-4556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOKPAyxCvM8WXlfM6CpcLTD4fMWicXzik',
    appId: '1:424836022854:ios:a0eeecfcf9e14fdf6f0047',
    messagingSenderId: '424836022854',
    projectId: 'smart-tourism-app-4556',
    storageBucket: 'smart-tourism-app-4556.firebasestorage.app',
    iosBundleId: 'com.microcode.smartTourismApp',
  );
}
